// import { response } from "express";
import request from "request";
// fetch(
//   "https://api.odcloud.kr/api/15077858/v1/uddi:a337f1a9-e6bf-4aaf-a46d-c8f2dc4fa5ee?page=1&perPage=10&serviceKey=5pIkioFukw1W8O%2F3pE8obsNXEojR%2BicwEkIcLhSHjnjbW6yIZI%2FLiLI3%2BEt0IAnghl89I41DVt8o5E3shOG39w%3D%3D"
// )
//   .then((response) => response.json())
//   .then((data) => console.log(data));

const url = "http://openapi.data.go.kr/openapi/service/rest/Covid19";
const SERVICE_KEY =
  "5pIkioFukw1W8O%2F3pE8obsNXEojR%2BicwEkIcLhSHjnjbW6yIZI%2FLiLI3%2BEt0IAnghl89I41DVt8o5E3shOG39w%3D%3D";
const requestUrl = `${url}?service=${SERVICE_KEY}&pageNo=1&numOfRows=10&startCreateDt=20200315&endCreateDt=20200315`;

request(requestUrl, (err, response, body) => {
  if (err) throw err;
  console.log(body);
});

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <h1>ㅎㅇㅎㅇ</h1>
    </div>
  );
}
